FROM ubuntu:18.04

LABEL authour="Abhishek Swain"
LABEL mail="abhiswain.it.2016@gmail.com"

RUN apt-get update 
RUN apt-get install -y gcc g++ build-essential libssl-dev cmake wget unzip python3-dev git

ARG path=libtorch-cxx11-abi-shared-with-deps-1.8.1+cpu

RUN wget --no-check-certificate https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.8.1%2Bcpu.zip \
    && unzip ${path}.zip \
    && rm -r ${path}.zip
    
RUN mkdir src

RUN git clone https://github.com/Abhiswain97/libtorch-cpu-docker.git \
    && cp /libtorch-cpu-docker/create_CMakeLists.py /src \
    && rm -r /libtorch-cpu-docker

COPY ./src /src

WORKDIR /src

RUN /bin/bash -c "python3 create_CMakeLists.py"

RUN /bin/bash -c "apt install make && mkdir build"

WORKDIR /src/build

RUN /bin/bash -c "cmake -DCMAKE_PREFIX_PATH=/libtorch .. && make"

CMD [ "./run" ]
